# Change these first
owner: tekhnee # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Tekhnee Login
    url: https://login.tekhn.ee
  - name: Tekhnee Cloud
    url: https://cloud.tekhn.ee
  - name: Tekhnee Learn
    url: https://learn.tekhn.ee
#  - name: Broken Site
#    url: https://thissitedoesnotexist.com
#  - name: Secret Site
#    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
  logoUrl: https://learn.tekhn.ee/pluginfile.php/1/core_admin/logo/0x150/1608497647/Tekhnee%20Logo
  name: System Status
  introTitle: "This status panel is updated every 5 minutes."
  introMessage: Courtesy of [Upptime](https://upptime.js.org/).
  navbar:
    - title: Status
      href: /
    - title: Contact
      href: mailto:info@tekhnee.org

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
