# Change these first
owner: tekhnee # Your GitHub username
repo: status # Your GitHub repository name

# Omit metadata from GitHub repo page.
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

# Add sites here
sites:
  - name: Tekhnee Login
    url: $LOGIN_LINK
  - name: Tekhnee Cloud
    url: $CLOUD_BENCHMARK_LINK
  - name: Tekhnee Learn
    url: $LEARN_LINK

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.tekhn.ee
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status
  logoUrl: https://learn.tekhn.ee/pluginfile.php/1/core_admin/logo/0x150/1608497647/Tekhnee%20Logo
  name: System status
# introTitle: "Updated every 5 minutes."
  introMessage: Updated every 5 minutes.
  navbar:
    - title: Tekhnee
      href: https://tekhnee.org
    - title: Support
      href: mailto:info@tekhnee.org
  robotsText: "User-agent: * \n Disallow: /"
  favicon: https://tekhn.ee/wp-content/uploads/2018/07/cropped-icon_blue_only_transparent-2-32x32.png
  css: "body {background: #dce4ef;}"

i18n:
  footer: "&nbsp;"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
